import { Event } from './slices/eventsSlice';

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Tech Meetup 2024',
    description: 'Join us for an evening of networking and tech talks',
    date: '2024-03-15',
    time: '18:00',
    location: 'Tech Hub',
    address: '123 Innovation Street',
    category: 'Technology',
    type: 'public',
    maxCapacity: 100,
    currentAttendees: 45,
    organizer: 'John Doe',
    thumbnail: 'https://example.com/tech-meetup.jpg',
    distance: 2.5,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '2',
    title: 'Yoga in the Park',
    description: 'Start your day with a peaceful yoga session',
    date: '2024-03-20',
    time: '07:00',
    location: 'Central Park',
    address: '456 Nature Way',
    category: 'Health & Wellness',
    type: 'public',
    maxCapacity: 50,
    currentAttendees: 20,
    organizer: 'Jane Smith',
    thumbnail: 'https://example.com/yoga.jpg',
    distance: 1.8,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '3',
    title: 'Cooking Workshop',
    description: 'Learn to cook authentic Italian cuisine',
    date: '2024-03-25',
    time: '14:00',
    location: 'Culinary Arts Center',
    address: '789 Food Street',
    category: 'Food & Drink',
    type: 'public',
    maxCapacity: 30,
    currentAttendees: 15,
    organizer: 'Chef Maria',
    thumbnail: 'https://example.com/cooking.jpg',
    distance: 4.2,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '4',
    title: 'Book Club Meeting',
    description: 'Discussion on "The Midnight Library"',
    date: '2024-03-28',
    time: '19:00',
    location: 'Local Library',
    address: '321 Book Avenue',
    category: 'Books & Literature',
    type: 'public',
    maxCapacity: 25,
    currentAttendees: 12,
    organizer: 'Sarah Johnson',
    thumbnail: 'https://example.com/book-club.jpg',
    distance: 0.7,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '5',
    title: 'Startup Pitch Night',
    description: 'Watch innovative startups pitch their ideas',
    date: '2024-04-01',
    time: '18:30',
    location: 'Innovation Center',
    address: '567 Startup Road',
    category: 'Business',
    type: 'public',
    maxCapacity: 150,
    currentAttendees: 80,
    organizer: 'Mike Chen',
    thumbnail: 'https://example.com/pitch-night.jpg',
    distance: 3.1,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '6',
    title: 'Live Music Night',
    description: 'Local bands performing live music',
    date: '2024-04-05',
    time: '20:00',
    location: 'The Music Hall',
    address: '890 Melody Lane',
    category: 'Music',
    type: 'public',
    maxCapacity: 200,
    currentAttendees: 120,
    organizer: 'David Wilson',
    thumbnail: 'https://example.com/music.jpg',
    distance: 1.2,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '7',
    title: 'Art Exhibition',
    description: 'Contemporary art showcase',
    date: '2024-04-10',
    time: '11:00',
    location: 'Modern Art Gallery',
    address: '234 Canvas Street',
    category: 'Arts',
    type: 'public',
    maxCapacity: 75,
    currentAttendees: 35,
    organizer: 'Emma Thompson',
    thumbnail: 'https://example.com/art.jpg',
    distance: 2.8,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '8',
    title: 'Basketball Tournament',
    description: 'Annual city basketball championship',
    date: '2024-04-15',
    time: '09:00',
    location: 'Sports Complex',
    address: '567 Court Road',
    category: 'Sports',
    type: 'public',
    maxCapacity: 300,
    currentAttendees: 150,
    organizer: 'Coach Johnson',
    thumbnail: 'https://example.com/basketball.jpg',
    distance: 3.5,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '9',
    title: 'Photography Workshop',
    description: 'Learn professional photography techniques',
    date: '2024-04-20',
    time: '13:00',
    location: 'Creative Studio',
    address: '789 Lens Avenue',
    category: 'Photography',
    type: 'public',
    maxCapacity: 20,
    currentAttendees: 8,
    organizer: 'Lisa Chen',
    thumbnail: 'https://example.com/photography.jpg',
    distance: 1.5,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '10',
    title: 'Gaming Tournament',
    description: 'Competitive gaming event with prizes',
    date: '2024-04-25',
    time: '15:00',
    location: 'Gaming Arena',
    address: '123 Controller Street',
    category: 'Gaming',
    type: 'public',
    maxCapacity: 100,
    currentAttendees: 65,
    organizer: 'Alex Rivera',
    thumbnail: 'https://example.com/gaming.jpg',
    distance: 0.9,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '11',
    title: 'Dance Workshop',
    description: 'Learn contemporary dance moves',
    date: '2024-04-28',
    time: '16:00',
    location: 'Dance Studio',
    address: '456 Rhythm Street',
    category: 'Dance',
    type: 'public',
    maxCapacity: 40,
    currentAttendees: 25,
    organizer: 'Maria Garcia',
    thumbnail: 'https://example.com/dance.jpg',
    distance: 2.1,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '12',
    title: 'Science Fair',
    description: 'Annual science exhibition for students',
    date: '2024-05-01',
    time: '10:00',
    location: 'Science Center',
    address: '789 Discovery Road',
    category: 'Science',
    type: 'public',
    maxCapacity: 500,
    currentAttendees: 300,
    organizer: 'Dr. James Wilson',
    thumbnail: 'https://example.com/science.jpg',
    distance: 3.8,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '13',
    title: 'Poetry Slam',
    description: 'Open mic poetry competition',
    date: '2024-05-05',
    time: '19:00',
    location: 'Cafe Poetry',
    address: '123 Verse Lane',
    category: 'Poetry',
    type: 'public',
    maxCapacity: 60,
    currentAttendees: 45,
    organizer: 'Sarah Lee',
    thumbnail: 'https://example.com/poetry.jpg',
    distance: 1.4,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '14',
    title: 'Fashion Show',
    description: 'Spring collection showcase',
    date: '2024-05-10',
    time: '20:00',
    location: 'Fashion Hall',
    address: '567 Style Avenue',
    category: 'Fashion',
    type: 'public',
    maxCapacity: 250,
    currentAttendees: 180,
    organizer: 'Emma Fashion',
    thumbnail: 'https://example.com/fashion.jpg',
    distance: 2.7,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '15',
    title: 'Coding Bootcamp',
    description: 'Intensive web development course',
    date: '2024-05-15',
    time: '09:00',
    location: 'Tech Academy',
    address: '890 Code Street',
    category: 'Technology',
    type: 'public',
    maxCapacity: 30,
    currentAttendees: 20,
    organizer: 'Alex Developer',
    thumbnail: 'https://example.com/coding.jpg',
    distance: 1.9,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '16',
    title: 'Marathon Training',
    description: 'Group training for upcoming marathon',
    date: '2024-05-20',
    time: '06:00',
    location: 'City Park',
    address: '234 Track Road',
    category: 'Sports',
    type: 'public',
    maxCapacity: 100,
    currentAttendees: 75,
    organizer: 'Coach Mike',
    thumbnail: 'https://example.com/marathon.jpg',
    distance: 0.5,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '17',
    title: 'Film Festival',
    description: 'Independent film screenings',
    date: '2024-05-25',
    time: '14:00',
    location: 'Cinema Hall',
    address: '345 Movie Street',
    category: 'Film',
    type: 'public',
    maxCapacity: 400,
    currentAttendees: 250,
    organizer: 'David Director',
    thumbnail: 'https://example.com/film.jpg',
    distance: 3.2,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '18',
    title: 'Language Exchange',
    description: 'Practice different languages with native speakers',
    date: '2024-06-01',
    time: '18:00',
    location: 'Language Cafe',
    address: '678 Talk Street',
    category: 'Language',
    type: 'public',
    maxCapacity: 50,
    currentAttendees: 30,
    organizer: 'Lingua Club',
    thumbnail: 'https://example.com/language.jpg',
    distance: 1.7,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '19',
    title: 'Chess Tournament',
    description: 'City chess championship',
    date: '2024-06-05',
    time: '10:00',
    location: 'Chess Club',
    address: '789 Strategy Road',
    category: 'Games',
    type: 'public',
    maxCapacity: 64,
    currentAttendees: 48,
    organizer: 'Grandmaster Paul',
    thumbnail: 'https://example.com/chess.jpg',
    distance: 2.3,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '20',
    title: 'Meditation Retreat',
    description: 'Weekend meditation and mindfulness',
    date: '2024-06-10',
    time: '08:00',
    location: 'Peace Center',
    address: '123 Zen Way',
    category: 'Wellness',
    type: 'public',
    maxCapacity: 40,
    currentAttendees: 25,
    organizer: 'Zen Master',
    thumbnail: 'https://example.com/meditation.jpg',
    distance: 4.5,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '21',
    title: 'Startup Networking',
    description: 'Connect with entrepreneurs and investors',
    date: '2024-06-15',
    time: '17:00',
    location: 'Business Hub',
    address: '456 Venture Street',
    category: 'Business',
    type: 'public',
    maxCapacity: 200,
    currentAttendees: 150,
    organizer: 'Venture Club',
    thumbnail: 'https://example.com/networking.jpg',
    distance: 2.9,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '22',
    title: 'Comedy Night',
    description: 'Stand-up comedy showcase',
    date: '2024-06-20',
    time: '20:00',
    location: 'Laugh Factory',
    address: '789 Joke Lane',
    category: 'Comedy',
    type: 'public',
    maxCapacity: 150,
    currentAttendees: 120,
    organizer: 'Comedy Club',
    thumbnail: 'https://example.com/comedy.jpg',
    distance: 1.6,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '23',
    title: 'Gardening Workshop',
    description: 'Learn urban gardening techniques',
    date: '2024-06-25',
    time: '11:00',
    location: 'Community Garden',
    address: '123 Green Street',
    category: 'Gardening',
    type: 'public',
    maxCapacity: 30,
    currentAttendees: 20,
    organizer: 'Green Thumb',
    thumbnail: 'https://example.com/gardening.jpg',
    distance: 0.8,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '24',
    title: 'AI Workshop',
    description: 'Introduction to artificial intelligence',
    date: '2024-07-01',
    time: '13:00',
    location: 'AI Lab',
    address: '456 Future Road',
    category: 'Technology',
    type: 'public',
    maxCapacity: 50,
    currentAttendees: 35,
    organizer: 'AI Expert',
    thumbnail: 'https://example.com/ai.jpg',
    distance: 3.4,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  },
  {
    id: '25',
    title: 'Music Festival',
    description: 'Three-day music festival',
    date: '2024-07-05',
    time: '12:00',
    location: 'Festival Grounds',
    address: '789 Music Valley',
    category: 'Music',
    type: 'public',
    maxCapacity: 5000,
    currentAttendees: 3500,
    organizer: 'Festival Organizers',
    thumbnail: 'https://example.com/festival.jpg',
    distance: 5.0,
    attendingEvents: [],
    attendees: [],
    rsvpRequests: []
  }
];

// Mock user data with attending and hosting events
export const mockUserData = {
  id: '1',
  name: 'John Doe',
  email: 'john@example.com',
  attendingEvents: ['1', '3', '5'], // IDs of events the user is attending
  hostingEvents: ['2', '4'], // IDs of events the user is hosting
}; 